Resolved issue #6 navbar added and improper alignment of the sections resolved
Its-Aman-Yadav/Community-Site pull request #66
Opened 2024-05-11 07:10 UTC by singhrimiumesh

**Changes Made**

Added a navbar to the page for better navigation.
Adjusted alignment of the sections to ensure proper layout.

**Details**

Added HTML structure for the navbar and included necessary CSS styles.
The sticky navbar enhances user experience by providing easy access to navigation options.
Ensured that the navbar spans the full width of the page for improved aesthetics.
Corrected alignment issues with the sections to maintain a consistent layout across different screen sizes.

**Screenshots**

Before : no navbar and improper alignment
![Screenshot 2024-05-11 123709](https://github.com/Its-Aman-Yadav/Community-Site/assets/115173871/11e4526a-d4a1-4762-ada8-e80d16eae88f)

Now  : Added Sticky Navbar and resolved the alignment issue
![Screenshot 2024-05-11 123728](https://github.com/Its-Aman-Yadav/Community-Site/assets/115173871/38d49fa8-7a69-4a1e-9b92-cc4a80b02c4f)

2024-05-12 04:08 UTC, singhrimiumesh commented
@Its-Aman-Yadav , and you please review and add the  label as gssoc24 and level1

2024-05-12 06:52 UTC, Its-Aman-Yadav commented
Navbar is not looking so good make it more clear and visible @singhrimiumesh

2024-05-12 06:52 UTC, Its-Aman-Yadav commented on css/style.css
> +  background-color: rgba(255, 255, 255, 0.2);
Please make it more clear

2024-05-12 06:52 UTC, Its-Aman-Yadav approved these changes

2024-05-16 06:59 UTC, bhaavvya commented
Heyy @singhrimiumesh can you please resolve the issues.

2024-05-16 12:06 UTC, Its-Aman-Yadav commented
Hey @singhrimiumesh are you still working on it?

2024-05-18 07:01 UTC, Its-Aman-Yadav commented
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/97724135/900ce561-24d1-4830-a28e-d2ff9ec3bc0a)
It is looking like this, please make changes

2024-05-18 07:01 UTC, Its-Aman-Yadav requested changes
remove the  old navbar and place yours

2024-06-22 06:44 UTC, closed without merging