solved the redirection issue
Its-Aman-Yadav/Community-Site pull request #95
Opened 2024-05-11 16:26 UTC by creativeadi

Before:

https://github.com/Its-Aman-Yadav/Community-Site/assets/153895524/bd311419-677e-467a-8ca6-0d01a781caf1

After:

https://github.com/Its-Aman-Yadav/Community-Site/assets/153895524/5727dd95-df61-4dd4-8682-c174c2930bca

2024-05-11 16:30 UTC, Its-Aman-Yadav requested changes
Please redirect them to our social handles

2024-05-11 16:50 UTC, creativeadi commented
@Its-Aman-Yadav  kindly provide with the respective social media handles

2024-05-12 06:55 UTC, Its-Aman-Yadav commented
here - https://www.linkedin.com/company/open-source-village/?viewAsMember=true
https://twitter.com/OpenSourceVill

2024-05-12 06:55 UTC, Its-Aman-Yadav commented on index.html
> +          <li><a href="https://www.twitter.com" target="_blank" class="fa fa-twitter wow bounceIn" data-wow-delay="0.9s"></a></li>
Change to our social media handles

2024-05-12 08:46 UTC, creativeadi commented
Uploading Screen Recording 2024-05-12 at 2.14.46 PM.mov…
@Its-Aman-Yadav 

fixed the redirection issue. the click on the social media handles directs the user to the official twitter and linkedin handles of this community. 

under GSSOC24

2024-05-12 08:47 UTC, creativeadi commented on index.html
> +          <li><a href="https://www.twitter.com" target="_blank" class="fa fa-twitter wow bounceIn" data-wow-delay="0.9s"></a></li>
fixed the changes as asked!

2024-05-13 12:54 UTC, closed without merging